import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionRouter from "./session";
import storageRouter from "./storage";
import usersRouter from "./users";
import chartersRouter from "./charters";
import approvalsRouter from "./approvals";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import portfoliosRouter from "./portfolios";
import workstreamsRouter from "./workstreams";
import projectStagesRouter from "./project_stages";
import documentsRouter from "./documents";
import issuesRouter from "./issues";
import messagesRouter from "./messages";
import resourcesRouter from "./resources";
import budgetRouter from "./budget";
import escalationRouter from "./escalation";
import scoringRouter from "./scoring";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import lessonsRouter from "./lessons";
import benefitsRouter from "./benefits";
import changeRequestsRouter from "./change_requests";
import meetingsRouter from "./meetings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionRouter);
router.use(storageRouter);
router.use(usersRouter);
router.use(chartersRouter);
router.use(approvalsRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(portfoliosRouter);
router.use(workstreamsRouter);
router.use(projectStagesRouter);
router.use(documentsRouter);
router.use(issuesRouter);
router.use(messagesRouter);
router.use(resourcesRouter);
router.use(budgetRouter);
router.use(escalationRouter);
router.use(scoringRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(lessonsRouter);
router.use(benefitsRouter);
router.use(changeRequestsRouter);
router.use(meetingsRouter);

export default router;
