import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionRouter from "./session";
import storageRouter from "./storage";
import usersRouter from "./users";
import chartersRouter from "./charters";
import approvalsRouter from "./approvals";
import projectsRouter from "./projects";
import dashboardRouter from "./dashboard";
import portfoliosRouter from "./portfolios";
import workstreamsRouter from "./workstreams";
import projectStagesRouter from "./project_stages";
import documentsRouter from "./documents";
import issuesRouter from "./issues";
import messagesRouter from "./messages";
import resourcesRouter from "./resources";
import budgetRouter from "./budget";
import escalationRouter from "./escalation";
import scoringRouter from "./scoring";
import notificationsRouter from "./notifications";
import aiRouter from "./ai";
import lessonsRouter from "./lessons";
import benefitsRouter from "./benefits";
import changeRequestsRouter from "./change_requests";
import meetingsRouter from "./meetings";
import templatesRouter from "./templates";
import pifsRouter from "./pifs";
import nfasRouter from "./nfas";
import userPreferencesRouter from "./user_preferences";
import nudgesRouter, { jobsRouter } from "./nudges";
import purchaseOrdersRouter from "./purchase_orders";
import teamsIntegrationRouter from "./integrations/teams";
import jiraIntegrationRouter from "./integrations/jira";
import adminIntegrationsRouter from "./admin/integrations";
import employeesRouter from "./employees";
import vendorMasterRouter from "./vendor_master";
import rfxRouter from "./rfx";
import stageSlasRouter from "./stage_slas";
import roleDirectoryRouter from "./role-directory";
import stageEscalationPolicyRouter from "./stage-escalation-policy";
import workRouter from "./work";
import doaMatrixRouter from "./doa_matrix";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionRouter);
router.use(storageRouter);
router.use(usersRouter);
router.use(chartersRouter);
router.use(approvalsRouter);
router.use(projectsRouter);
router.use(dashboardRouter);
router.use(portfoliosRouter);
router.use(workstreamsRouter);
router.use(projectStagesRouter);
router.use(documentsRouter);
router.use(issuesRouter);
router.use(messagesRouter);
router.use(resourcesRouter);
router.use(budgetRouter);
router.use(escalationRouter);
router.use(scoringRouter);
router.use(notificationsRouter);
router.use(aiRouter);
router.use(lessonsRouter);
router.use(benefitsRouter);
router.use(changeRequestsRouter);
router.use(meetingsRouter);
router.use(templatesRouter);
router.use(pifsRouter);
router.use(nfasRouter);
router.use(userPreferencesRouter);
router.use(nudgesRouter);
router.use(jobsRouter);
router.use(purchaseOrdersRouter);
router.use(teamsIntegrationRouter);
router.use(jiraIntegrationRouter);
router.use("/admin/integrations", adminIntegrationsRouter);
router.use(employeesRouter);
router.use(vendorMasterRouter);
router.use(rfxRouter);
router.use(stageSlasRouter);
router.use(roleDirectoryRouter);
router.use(stageEscalationPolicyRouter);
router.use(workRouter);
router.use(doaMatrixRouter);

export default router;
