import { useState, useEffect } from "react";
import { jsPDF } from "jspdf";
import {
 useListProjectStages,
 useUpdateProjectStage,
 useCreateDocument,
} from "@workspace/api-client-react";
import { useUserStore } from "../../lib/store";
import { useToast } from "@/hooks/use-toast";
import { useQueryClient } from "@tanstack/react-query";
import { FileText } from "lucide-react";

export function ClosureReport({ projectId }: { projectId: number }) {
 const { userId } = useUserStore();
 const { toast } = useToast();
 const queryClient = useQueryClient();
 const { data: stageRecords = [] } = useListProjectStages(projectId);
 const updateStage = useUpdateProjectStage();
 const createDocument = useCreateDocument();

 const closureRecord = (
 stageRecords as Array<{ id: number; stage: string; notes?: string | null }>
 ).find((r) => r.stage === "project_closure");

 const parsedNotes = (() => {
 try { return closureRecord?.notes ? (JSON.parse(closureRecord.notes) as Record<string, unknown>) : {}; }
 catch { return {}; }
 })();

 const [lessonsWentWell, setLessonsWentWell] = useState(
 (parsedNotes.__lessonsWentWell as string | undefined) ?? "",
 );
 const [lessonsImprove, setLessonsImprove] = useState(
 (parsedNotes.__lessonsImprove as string | undefined) ?? "",
 );
 const [lessonsRecs, setLessonsRecs] = useState(
 (parsedNotes.__lessonsRecs as string | undefined) ?? "",
 );
 const reportGeneratedAt = parsedNotes.__closureReportGeneratedAt as string | undefined;

 useEffect(() => {
 if (closureRecord?.notes) {
 try {
 const p = JSON.parse(closureRecord.notes) as Record<string, unknown>;
 if (p.__lessonsWentWell) setLessonsWentWell(p.__lessonsWentWell as string);
 if (p.__lessonsImprove) setLessonsImprove(p.__lessonsImprove as string);
 if (p.__lessonsRecs) setLessonsRecs(p.__lessonsRecs as string);
 } catch {}
 }
 // eslint-disable-next-line react-hooks/exhaustive-deps
 }, [closureRecord?.id]);

 function saveAndGenerate() {
 if (!lessonsWentWell || !lessonsImprove || !lessonsRecs) return;
 const generatedAt = new Date().toISOString();
 const nextNotes = {
 ...parsedNotes,
 __lessonsWentWell: lessonsWentWell,
 __lessonsImprove: lessonsImprove,
 __lessonsRecs: lessonsRecs,
 __closureReportGeneratedAt: generatedAt,
 };

 if (closureRecord?.id) {
 updateStage.mutate(
 { id: closureRecord.id, data: { notes: JSON.stringify(nextNotes) } },
 { onError: () => toast({ title: "Failed to save lessons learned", variant: "destructive" }) },
 );
 }

 const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
 const pageW = doc.internal.pageSize.getWidth();
 const marginX = 20;
 const contentW = pageW - marginX * 2;

 doc.setFillColor(79, 70, 229);
 doc.rect(0, 0, pageW, 18, "F");
 doc.setTextColor(255, 255, 255);
 doc.setFontSize(13);
 doc.setFont("helvetica", "bold");
 doc.text("PROJECT CLOSURE REPORT", marginX, 12);
 doc.setFontSize(8);
 doc.setFont("helvetica", "normal");
 doc.text(
 `Generated: ${new Date(generatedAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
 pageW - marginX,
 12,
 { align: "right" },
 );

 let y = 28;
 const addSection = (title: string, body: string) => {
 doc.setFont("helvetica", "bold");
 doc.setFontSize(11);
 doc.setTextColor(55, 65, 81);
 doc.text(title, marginX, y);
 y += 2;
 doc.setDrawColor(79, 70, 229);
 doc.setLineWidth(0.4);
 doc.line(marginX, y, marginX + contentW, y);
 y += 5;
 doc.setFont("helvetica", "normal");
 doc.setFontSize(10);
 doc.setTextColor(75, 85, 99);
 const lines = doc.splitTextToSize(body, contentW);
 lines.forEach((line: string) => {
 if (y > 270) { doc.addPage(); y = 20; }
 doc.text(line, marginX, y);
 y += 5.5;
 });
 y += 6;
 };

 addSection("What Went Well", lessonsWentWell);
 addSection("What Could Be Improved", lessonsImprove);
 addSection("Recommendations", lessonsRecs);
 addSection(
 "Outcome",
 "Project formally closed and archived. All deliverables have been accepted and signed off by relevant stakeholders. Knowledge transfer complete and transition to BAU operations confirmed.",
 );

 doc.setFontSize(8);
 doc.setTextColor(156, 163, 175);
 doc.text("Confidential — Generated by Project Hub", marginX, 287);
 doc.text("Page 1", pageW - marginX, 287, { align: "right" });

 const pdfBlob = doc.output("blob");
 const fileName = `closure_report_${generatedAt.slice(0, 10)}.pdf`;

 fetch("/api/storage/uploads/request-url", {
 method: "POST",
 headers: { "Content-Type": "application/json" },
 body: JSON.stringify({ name: fileName, size: pdfBlob.size, contentType: "application/pdf" }),
 })
 .then(async (r) => {
 if (!r.ok) throw new Error("Failed to get upload URL");
 return r.json() as Promise<{ uploadURL: string; objectPath: string }>;
 })
 .then(
 ({ uploadURL, objectPath }) =>
 new Promise<string>((resolve, reject) => {
 const xhr = new XMLHttpRequest();
 xhr.open("PUT", uploadURL);
 xhr.setRequestHeader("Content-Type", "application/pdf");
 xhr.onload = () => {
 if (xhr.status >= 200 && xhr.status < 300) resolve(objectPath);
 else reject(new Error(`Upload failed: ${xhr.status}`));
 };
 xhr.onerror = () => reject(new Error("Network error"));
 xhr.send(pdfBlob);
 }),
 )
 .then((objectPath) => {
 createDocument.mutate(
 {
 id: projectId,
 data: {
 name: "Closure Report",
 stage: "project_closure",
 fileUrl: `/api/storage${objectPath}`,
 fileType: "application/pdf",
 fileSize: pdfBlob.size,
 uploadedBy: userId ?? undefined,
 description: `Auto-generated Closure Report — ${new Date(generatedAt).toLocaleDateString()}`,
 },
 },
 {
 onSuccess: () => {
 toast({ title: "Closure Report PDF generated and uploaded to document repository" });
 void queryClient.invalidateQueries({ queryKey: ["/api/projects", projectId, "documents"] });
 },
 onError: () =>
 toast({ title: "Failed to register Closure Report document", variant: "destructive" }),
 },
 );
 })
 .catch(() =>
 toast({ title: "Closure Report upload failed — storage unavailable", variant: "destructive" }),
 );
 }

 return (
 <div className="rounded-xl p-4 mt-4" style={{ background: "hsl(var(--muted) / 0.4)", border: "1px solid hsl(var(--border))" }}>
 <h4 className="text-sm font-bold text-muted-foreground mb-3 flex items-center gap-2">
 <FileText size={14} className="text-muted-foreground" />
 Lessons Learned
 </h4>
 <div className="space-y-3">
 <div>
 <label className="text-xs font-semibold text-muted-foreground block mb-1">What Went Well</label>
 <textarea
 rows={2}
 value={lessonsWentWell}
 onChange={(e) => setLessonsWentWell(e.target.value)}
 placeholder="Describe what worked well in this project..."
 className="w-full rounded-lg px-3 py-2 text-sm border border-border bg-card outline-none resize-none focus:border-primary/40"
 />
 </div>
 <div>
 <label className="text-xs font-semibold text-muted-foreground block mb-1">What Could Be Improved</label>
 <textarea
 rows={2}
 value={lessonsImprove}
 onChange={(e) => setLessonsImprove(e.target.value)}
 placeholder="Identify areas for improvement..."
 className="w-full rounded-lg px-3 py-2 text-sm border border-border bg-card outline-none resize-none focus:border-primary/40"
 />
 </div>
 <div>
 <label className="text-xs font-semibold text-muted-foreground block mb-1">Recommendations</label>
 <textarea
 rows={2}
 value={lessonsRecs}
 onChange={(e) => setLessonsRecs(e.target.value)}
 placeholder="Recommendations for future similar projects..."
 className="w-full rounded-lg px-3 py-2 text-sm border border-border bg-card outline-none resize-none focus:border-primary/40"
 />
 </div>
 <button
 onClick={saveAndGenerate}
 disabled={!lessonsWentWell || !lessonsImprove || !lessonsRecs}
 className={`w-full py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-40 disabled:cursor-not-allowed ${reportGeneratedAt ? "bg-success/10 text-success border border-success/30" : "bg-primary text-primary-foreground hover:bg-primary/90"}`}
 
 >
 {reportGeneratedAt
 ? `✓ Report Saved (${new Date(reportGeneratedAt).toLocaleDateString()})`
 : "Save & Generate Closure Report"}
 </button>
 {reportGeneratedAt && (
 <p className="text-xs text-success text-center">
 Lessons learned persisted to DB. Document record created for sign-off.
 </p>
 )}
 </div>
 </div>
 );
}
