-- CAPEX DOA bands from 'Granules DOA-23.02.26.xlsx'. Creates table if missing + idempotent seed.
BEGIN;
CREATE TABLE IF NOT EXISTS pmo_doa_matrix (
  id serial PRIMARY KEY,
  entity text NOT NULL DEFAULT '*',
  category text NOT NULL DEFAULT '*',
  kind text NOT NULL DEFAULT '*',
  min_inr numeric(15,2) NOT NULL DEFAULT '0',
  max_inr numeric(15,2),
  approver_roles jsonb NOT NULL DEFAULT '[]'::jsonb,
  active boolean NOT NULL DEFAULT true,
  label text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
DELETE FROM pmo_doa_matrix WHERE notes = 'seed:capex-doa-23.02.26';
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-PFI (1300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "Faizuddin.md@granulesindia.com"}, {"designation": "Associate Vice President", "email": "sudhakar.babu@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP PFI-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-FD (1400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "Faizuddin.md@granulesindia.com"}, {"designation": "Associate Vice President", "email": "sudhakar.babu@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-PFI (1300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "Madhubabu.Yedida@granulesindia.com"}, {"designation": "Vice President", "email": "Ramesh.CG@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP PFI-QA','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-FD (1400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "Madhubabu.Yedida@granulesindia.com"}, {"designation": "Vice President", "email": "Ramesh.CG@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP FD-QA','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-PFI (1300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Assistant General Manager", "email": "Sankar.Thirusangu@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Yogeesha.Sanil@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP PFI-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-FD (1400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Assistant General Manager", "email": "Sankar.Thirusangu@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Yogeesha.Sanil@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP FD-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-PFI (1300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Deputy General Manager", "email": "Rameshbabu.Balina@granulesindia.com"}, {"designation": "Vice President", "email": "Ramesh.CG@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP PFI- RD QC2','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-FD (1400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Deputy General Manager", "email": "Rameshbabu.Balina@granulesindia.com"}, {"designation": "Vice President", "email": "Ramesh.CG@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP FD- RD QC2','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('API Unit-I (BPL1) (1000)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Deputy General Manager", "email": "VijayaSekhar.Kondapi@granulesindia.com"}, {"designation": "Associate Vice President", "email": "PulSingh.Vadithe@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-BPL1-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('API Unit-I (BPL1) (1000)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Deputy General Manager", "email": "PavanSankaramanchi@granulesindia.com"}, {"designation": "Associate Vice President", "email": "PulSingh.Vadithe@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-BPL1-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('API Unit-I (BPL1) (1000)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "rajesh.kuchipudi@granulesindia.com"}, {"designation": "Associate Vice President", "email": "PulSingh.Vadithe@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-BPL1-QA','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Vizag1 – API Unit IV (2100)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Senior Manager", "email": "Parameswaran.Sadasivam@granulesindia.com"}, {"designation": "Deputy General Manager", "email": "Sameer.Shaikh@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-Vsk1-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('VSK-2 (2200)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "SelvaKumar.D@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Naveendiran.Loganathan@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-VSK2 API-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('VSK-2 (2300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "SelvaKumar.D@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Naveendiran.Loganathan@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-VSK2 Onco API-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('VSK-2 (2400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "SelvaKumar.D@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Naveendiran.Loganathan@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-VSK2 Onco FD-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('VSK-2 (2200)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "General Manager", "email": "KaleswaraRao.T@granulesindia.com"}, {"designation": "Associate Vice President", "email": "Naveendiran.Loganathan@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-VSK2 API -QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Corporate Office (9000)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Senior Executive", "email": "Ramakrishna.Devarasetty@granulesindia.com"}, {"designation": "Vice President", "email": "Karthick.Raja@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-Corp IT','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('GLS (6300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Associate Vice President", "email": "Sumesh.Nair@granulesindia.com"}, {"designation": "General manager", "email": "Sandeep.Bankar@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GLS-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('GLS (6300)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Associate Vice President", "email": "Prashanth.Vadde@granulesindia.com"}, {"designation": "General manager", "email": "Sandeep.Bankar@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GLS-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Gagillapur-FD (1400)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Associate Vice President", "email": "Yogeesha.Sanil@granulesindia.com"}, {"designation": "Vice President", "email": "Ramesh.CG@granulesindia.com"}, {"designation": "President", "email": "Ramraj.Rangarajalu@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-GGP FD-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('CZRO (6110)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Associate Vice President", "email": "thrilok.peela@granulesindia.com"}, {"designation": "CEO", "email": "ravindraraju.ds@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-CZRO','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Jeedimetla (1100)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Senior Manager", "email": "Venkateswararao.Tummala@granulesindia.com"}, {"designation": "General Manager", "email": "Srinivasa.Guntu@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-JDM-Eng.','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Jeedimetla (1100)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Senior Manager", "email": "sunitha.uppalapati@granulesindia.com"}, {"designation": "General Manager", "email": "Srinivasa.Guntu@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Capex-JDM-QC','seed:capex-doa-23.02.26');
INSERT INTO pmo_doa_matrix (entity,category,kind,min_inr,max_inr,approver_roles,active,label,notes) VALUES ('Jeedimetla (1100)','Capex','Capex Material & Services',1500000,NULL,'[{"designation": "Assistant General Manager", "email": "Satish.Undavalli@granulesindia.com"}, {"designation": "General Manager", "email": "Srinivasa.Guntu@granulesindia.com"}, {"designation": "President", "email": "baskaran.pn@granulesindia.com"}, {"designation": "CFO", "email": "Mukesh.Surana@granulesindia.com"}, {"designation": "CMD", "email": "kprasad@granulesindia.com"}]'::jsonb,true,'Czpex-JDM-R&D QA2','seed:capex-doa-23.02.26');
COMMIT;
